### Emulate the get request for the root directory to load the frontend
GET http://localhost:3002


### Emulate the post request to register a user
POST http://localhost:3002/auth/register
Content-Type: application/json

{
    "username": "Kayongo",
    "password": "testpassword"
}

### Emulate the post request to login a user

POST http://localhost:3002/auth/login
Content-Type: application/json

{
    "username": "Kayongo",
    "password": "testpassword"
}


### Emulate a get request for the todos (protected)
GET http://localhost:3002/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImlhdCI6MTc4MTc4MjM0MywiZXhwIjoxNzgxODY4NzQzfQ.eJFfTZIMjW-BaP9Ked5lTkrqH6-VIJpKlMueFb5LxRk