### Emulate the get request for the root directory to load the frontend
GET http://localhost:3002


### Emulate the post request to register a user
POST http://localhost:3002/auth/register
Content-Type: application/json

{
    "username": "Kayo",
    "password": "testpassword"
}

### Emulate the post request to login a user

POST http://localhost:3002/auth/login
Content-Type: application/json

{
    "username": "Kayo",
    "password": "testpassword"
}


### Emulate a get request for the todos (protected)
GET http://localhost:3002/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzgyMDUwMTgzLCJleHAiOjE3ODIxMzY1ODN9.LJaXZuuvLgeXYXmzdxGwC-A2Wr_hlHxGuPDsh8VbWtw



### Emulate a post request to create a todo (protected)
POST http://localhost:3002/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzgyMDUwMTgzLCJleHAiOjE3ODIxMzY1ODN9.LJaXZuuvLgeXYXmzdxGwC-A2Wr_hlHxGuPDsh8VbWtw
Content-Type: application/json

{
    "task": "Finish the todo app"
}


### Emulate a put request to update the todo status (protected)

PUT http://localhost:3002/todos/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzgyMDUwMTgzLCJleHAiOjE3ODIxMzY1ODN9.LJaXZuuvLgeXYXmzdxGwC-A2Wr_hlHxGuPDsh8VbWtw
Content-Type: application/json

{
    "completed": 1
}


### Emulate a delete request to delete a todo (protected)
DELETE http://localhost:3002/todos/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzgyMDUwMTgzLCJleHAiOjE3ODIxMzY1ODN9.LJaXZuuvLgeXYXmzdxGwC-A2Wr_hlHxGuPDsh8VbWtw