### Emulate the get request for the root directory to load the frontend
GET http://localhost:3002


### Emulate the post request to register a user
POST http://localhost:3002/auth/register
Content-Type: application/json

{
    "username": "hard",
    "password": "testpassword"
}

### Emulate the post request to login a user

POST http://localhost:3002/auth/login
Content-Type: application/json

{
    "username": "hard",
    "password": "testpassword"
}